languaje: node_js
node_js:
- 14
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: OIGpYE60dV5Cd6wKOViN7A4IQfctxGDVNqZgWLv+q78VUb/pkLQCcQyGqAL8XxuOi/SkAqNyTUo7dYt8+mRN73vyAWfz4TOdsqSztIW3t944JYdFBKOm1wNU61hqNLEUSNLbMDfbm5ueSD2B1WxkYV7jCAA7s4T/dWF6GzI8sealtUn0dpKtqEDjQxVtfQXhNJdAj9h2wp86Un4wrRpRA3hNwV8jYKnbvl5S5cbiO/RyLSdOTQJyhHPP7Na4TTu/T6GOaQZpBa8B1dSjv1CuC0nWc1RFAaaQAfQ6vIOuZW1BhJ/n6ku6q4IUVBi9IEBcSxfEcPbz73W73U+jGMsTlbkh1NCNkUEGWeI7iPNTNUgG3KrsWMh28EeUnZcv0dngbU3a8EoOBey9/EUYKJepJAyQXOMeaTqOrvcT6F9jlk/6LLdaJ1iCYShZs2RB4W4Fny0JEZVvmD1TGaIk1aZuTRK21FqHaMPEF97BOmkqmMsEb5otAUzRiLR4ldMn9knA+Xk9sEADn/N+bNVSnho5xvk1b5zUw2KOAGmwgowobsdDlPS3IQUTxcL2cYZwXvLPk+/FVHO014vtsNs+82pg9FcbSuCYCcl9mzlLrzaF57psjFdXtA42TZo1GjWg9eeDigJI6d2IC7p1mZYTSaH55NnMpNJFlM/2FDy75YWaDPA=
  app:
    develop: fiuba-taller-2-web-admin-st
    master: fiuba-taller-2-web-admin
